create table if not exists public.lyrics (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  youtube_url text,
  spotify_url text,
  lyrics text not null,
  created_at timestamptz not null default now()
);

alter table public.lyrics
  add column if not exists youtube_url text,
  add column if not exists spotify_url text;

create table if not exists public.artists (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  bio text not null default '',
  genre text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.song_requests (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  note text,
  created_at timestamptz not null default now()
);

alter table public.artists
  add column if not exists slug text,
  add column if not exists bio text not null default '',
  add column if not exists genre text not null default '',
  add column if not exists created_at timestamptz not null default now();

alter table public.song_requests
  add column if not exists title text,
  add column if not exists artist text,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now();

update public.artists
set genre = ''
where coalesce(btrim(genre), '') = coalesce(btrim(bio), '');

update public.artists
set slug = trim(both '-' from regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g'))
where slug is null or btrim(slug) = '';

alter table public.artists
  alter column slug set not null;

do $$
declare
  artists_id_type text;
begin
  select data_type
  into artists_id_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'artists'
    and column_name = 'id';

  if artists_id_type = 'uuid' then
    execute 'alter table public.lyrics add column if not exists artist_id uuid';
  else
    execute 'alter table public.lyrics add column if not exists artist_id bigint';
  end if;
end $$;

do $$
declare
  has_fk boolean;
begin
  select exists (
    select 1
    from information_schema.table_constraints
    where constraint_schema = 'public'
      and table_name = 'lyrics'
      and constraint_name = 'lyrics_artist_id_fkey'
      and constraint_type = 'FOREIGN KEY'
  )
  into has_fk;

  if not has_fk then
    execute 'alter table public.lyrics add constraint lyrics_artist_id_fkey foreign key (artist_id) references public.artists(id) on delete set null';
  end if;
end $$;

update public.lyrics l
set artist_id = a.id
from public.artists a
where l.artist_id is null
  and lower(l.artist) = lower(a.name);

update public.lyrics l
set artist_id = a.id
from public.artists a
where l.artist_id is null
  and (
    lower(l.artist) like lower(a.name || ',%')
    or lower(l.artist) like lower('%,' || a.name)
    or lower(l.artist) like lower('%,' || a.name || ',%')
  );

update public.lyrics l
set artist = a.name
from public.artists a
where l.artist_id = a.id
  and l.artist <> a.name;

alter table public.lyrics enable row level security;
alter table public.artists enable row level security;
alter table public.song_requests enable row level security;

drop policy if exists "Allow public read lyrics" on public.lyrics;
drop policy if exists "Allow public insert lyrics" on public.lyrics;
drop policy if exists "Allow public update lyrics" on public.lyrics;
drop policy if exists "Allow public read artists" on public.artists;
drop policy if exists "Allow public write artists" on public.artists;
drop policy if exists "Allow public insert song requests" on public.song_requests;

create policy "Allow public read lyrics"
on public.lyrics
for select
to anon
using (true);

create policy "Allow public insert lyrics"
on public.lyrics
for insert
to anon
with check (true);

create policy "Allow public update lyrics"
on public.lyrics
for update
to anon
using (true)
with check (true);

create policy "Allow public read artists"
on public.artists
for select
to anon
using (true);

create policy "Allow public write artists"
on public.artists
for all
to anon
using (true)
with check (true);

create policy "Allow public insert song requests"
on public.song_requests
for insert
to anon
with check (true);
